new structure virtualappliance menu

diff --git a/update b/update
--- a/update
+++ b/update
@@ -10,13 +10,21 @@ if [ -d /loginvsi/hosting ]; then
     rm -rf /loginvsi/hosting
 fi 
 
-
+composefilepath=$(grep "COMPOSEFILE=" < /loginvsi/.env | cut -d "=" -f2)
+if [ -n "$composefilepath" ]; then    
+        newcomposefilepath=${composefilepath//\/compose/\/hosting}
+        newenvfilepath=${newcomposefilepath//\/docker-compose.yml/\/.env}
+    else
+        # composefile entry for composefile doesn't exist yet, this can only be an internalDb variant, since this entry was introduced before adding ExternalDB support
+        composefilepath="/loginvsi/docker-compose.yml"
+        newenvfilepath="/loginvsi/hosting/latest/InternalDb/.env"
+        echo "COMPOSEFILE=/loginvsi/compose/InternalDB/docker-compose.yml" >>/loginvsi/.env  # add the entry so we know what composefile to start in the future
+    fi 
 
 # Get the hosting repo
-while read -r repo branch hostingfolder; do             
-    #set this appliance to the release branch, even it was originally build from master branch
-    branch="release"
-    echo $repo $branch $hostingfolder > /root/.hosting 
+while read -r repo branch _; do
+    
+                    
     if [ -z $offline ]; then 
         if [ -n "$internal" ]; then
             echo "Performing internal update from $2" 
@@ -33,14 +41,10 @@ while read -r repo branch hostingfolder; do
     else
         # offline updater, copy hosting files from hosting folder on iso        
         cp -rf /mnt/cdrom/hosting/ .
-    fi
-    if [ ! -f /loginvsi/hosting/$hostingfolder/docker-compose.yml ]; then 
-		echo "Cloning hosting repo has failed, unable to continue update, please contact support@loginvsi.com"
-		exit 1
-	fi
+    fi    
     if [ -z $recurse ]; then 
-        currentversion=$(grep "Version__Number" < /loginvsi/docker-compose.yml | cut -d':' -f2 | cut -d"'" -f2 | tail -1)    
-        newversion=$(grep "Version__Number" < /loginvsi/hosting/$hostingfolder/docker-compose.yml | cut -d':' -f2 | cut -d"'" -f2 | tail -1)
+        currentversion=$(grep "Version__Number" < $composefilepath | cut -d':' -f2 | cut -d"'" -f2 | tail -1)            
+        newversion=$(grep "Version__Number" < $newcomposefilepath | cut -d':' -f2 | cut -d"'" -f2 | tail -1)
         echo "This appliance is going to be updated to the latest version. Please make sure you have a backup of the system and data before proceeding."
         read -rep "Are you sure you want to update from $currentversion to $newversion [y/N]: " PROCEED </dev/tty
         DEFAULT="n"
@@ -60,22 +64,25 @@ while read -r repo branch hostingfolder; do
             echo -n "Updating from $currentversion to $newversion..."
         fi
         # copy latest compose file from hosting
-        echo "Copying hosting/$hostingfolder/docker-compose.yml to /loginvsi" &> /loginvsi/update.log
+        echo "Copying hosting/latest to /loginvsi/compose" &> /loginvsi/update.log
         
-        # copy the new compose file
-        cp -f "/loginvsi/hosting/$hostingfolder/docker-compose.yml" /loginvsi
+       
         # get the status of trusted/untrusted certs
-        currentcertsetting=$(grep SystemConfiguration__AllowUntrustedCertificates < /loginvsi/docker-compose.yml | head -n1 | cut -d':' -f2 | cut -d '"' -f2)
+        currentcertsetting=$(grep SystemConfiguration__AllowUntrustedCertificates < $composefilepath | head -n1 | cut -d':' -f2 | cut -d '"' -f2)
+
+        # copy the new compose files
+        cp -Rf "/loginvsi/hosting/latest" /loginvsi/compose
+
         if [ -n "$currentcertsetting" ]; then 
             # persist status of trusted/untrusted certs
             if [ $currentcertsetting == "true" ]; then
-                sed -i 's,SystemConfiguration__AllowUntrustedCertificates: "false",SystemConfiguration__AllowUntrustedCertificates: "true",g' /loginvsi/docker-compose.yml
+                sed -i 's,SystemConfiguration__AllowUntrustedCertificates: "false",SystemConfiguration__AllowUntrustedCertificates: "true",g' $composefilepath
             else
-                sed -i 's,SystemConfiguration__AllowUntrustedCertificates: "true",SystemConfiguration__AllowUntrustedCertificates: "false",g' /loginvsi/docker-compose.yml
+                sed -i 's,SystemConfiguration__AllowUntrustedCertificates: "true",SystemConfiguration__AllowUntrustedCertificates: "false",g' $composefilepath
             fi
         fi
         # Check if any new entries in new .env and add them to the current .env
-        for i in $(diff -y hosting/$hostingfolder/.env /loginvsi/.env | grep ">" | cut -d ">" -f2 | xargs); do
+        for i in $(diff -y $newenvfilepath /loginvsi/.env | grep ">" | cut -d ">" -f2 | xargs); do
             echo $i >> .env
         done
     fi
@@ -94,7 +101,11 @@ if [[ "${PROCEED}" == "y" ]]; then
     chown root:root /usr/bin/loginvsid
     systemctl disable loginvsid &>> /loginvsi/update.log
     systemctl enable loginvsid &>> /loginvsi/update.log
-
+    # remove old docker-cleanup daemon service if it exists
+    if [ $(systemctl | grep -c docker-cleanup) -gt 0 ]; then
+        systemctl stop docker-cleanup
+        systemctl disable docker-cleanup        
+    fi
     if [ ! -f /etc/docker/daemon.json ]; then
         cp -f update/daemon.json /etc/docker
     fi
@@ -102,64 +113,14 @@ if [[ "${PROCEED}" == "y" ]]; then
 
     # clean up hosting repo
     rm -rf /loginvsi/hosting
-
-
-
-    # create new db folders if needed
-    for f in $(grep "{DB_ROOT}" < /loginvsi/docker-compose.yml)
-    do 
-        folder=$(echo $f | cut -d"-" -f2 | cut -d"/" -f2 | cut -d":" -f1) 
-        if [ -n "$folder" ]; then
-            if [ ! -d /loginvsi/data/$folder ]; then        
-                mkdir /loginvsi/data/$folder; 
-            fi
-        fi
-    done
-
-    # check if all secrets have been created
-    existingsecrets=$(docker secret ls --format "{{.Name}}")
-    composesecrets=""
-    secretsstartlinenumber=$(grep -n "^secrets:" /loginvsi/docker-compose.yml | cut -d':' -f1)
-    servicesstartlinenumber=$(grep -n "^services:" /loginvsi/docker-compose.yml | cut -d':' -f1)
-    OLDIFS=$IFS
-    IFS=$'\n'
-    for line in $(tail -n+$secretsstartlinenumber /loginvsi/docker-compose.yml | head -n $(($servicesstartlinenumber-$secretsstartlinenumber)) | grep "^ "); do
-        
-        if [[ -z $(echo $line | cut -d':' -f2) ]]; then 
-            composesecrets+=$(echo $line | cut -d':' -f1 | xargs)
-            composesecrets+=" "
-        fi
-    done
-    IFS=$OLDIFS
-
-    for newsecret in $(echo $existingsecrets $composesecrets | tr ' ' '\n' | sort | uniq -u); do 
-        case "$newsecret" in
-            *_SSL_CERTIFICATE|*_SSL_CERTIFICATE_KEY) 
-                # we do nothing with SSL_certs during update
-                ;;
-            LAUNCHER_SECRET)
-                echo "Found new secret: $newsecret, creating it now..." &>> /loginvsi/update.log
-                openssl rand -hex 40 | head -c 40 | tr [:lower:] [:upper:] | docker secret create LAUNCHER_SECRET - &>> /loginvsi/update.log
-                ;; 
-            ENGINE_SECRET)
-                echo "Found new secret: $newsecret, creating it now..." &>> /loginvsi/update.log
-                openssl rand -hex 40 | head -c 40 | tr [:lower:] [:upper:] | docker secret create ENGINE_SECRET - &>> /loginvsi/update.log
-                ;; 
-            EVENTLOGGER_SECRET)
-                 echo "Found new secret: $newsecret, creating it now..." &>> /loginvsi/update.log
-                openssl rand -hex 40 | head -c 40 | tr [:lower:] [:upper:] | docker secret create EVENTLOGGER_SECRET - &>> /loginvsi/update.log
-                ;;
-            *) 
-                echo "WARNING: Found new secret: $newsecret, but this updater does not know how to handle it!" 
-                ;;
-        esac    
-    done
-
+    
+    composefilepath=$(grep "COMPOSEFILE=" < /loginvsi/.env | cut -d "=" -f2)
 
     if [ -z $offline ]; then 
         # pull the new images from dockerhub if we are online
         base64 -d < /root/.play | docker login -u vsiplayaccount --password-stdin &>> /loginvsi/update.log
-        cd /loginvsi || (echo "Failed to find /loginvsi folder" && exit 1)
+        
+        cd ${composefilepath//docker-compose.yml/} || (echo "Failed to find ${composefilepath//docker-compose.yml/} folder" && exit 1)
         docker-compose pull --quiet &>>/loginvsi/update.log 
         if [ $? != 0 ]; then 
          echo "Something went wrong during pulling of the images from docker hub, please verify this appliance can connect to index.docker.io" && exit 1
@@ -167,59 +128,16 @@ if [[ "${PROCEED}" == "y" ]]; then
         #for image in $(grep image: < /loginvsi/docker-compose.yml | cut -d':' -f2,3| sort | uniq);do
         #    docker pull $(echo $image | xargs) &>> /loginvsi/update.log
         #done
-        docker pull portainer &>> /loginvsi/update.log
+        #docker pull portainer &>> /loginvsi/update.log
         docker logout &>> /loginvsi/update.log
     else
-        # offline update
-        # import registry
-        docker rm -f $(docker ps --filter name=update_registry -q) &>> /loginvsi/update.log
-        docker rmi registry:2 &>> /loginvsi/update.log
-        echo "$(date) Importing docker registry image, this might take a while"
-        gunzip -c /mnt/cdrom/registry.tar.gz | docker image import - registry:2 &>> /loginvsi/update.log
-        rm -rf /tmp/registry_data
-        mkdir -p /tmp/registry_data
-        tar -zxf /mnt/cdrom/registry_data.tar.gz --directory /tmp/registry_data &>> /loginvsi/update.log
-        docker run -v /tmp/registry_data:/var/lib/registry -d -p 55555:5000 --entrypoint /entrypoint.sh --name update_registry registry:2 /etc/docker/registry/config.yml &>> /loginvsi/update.log
-        echo "$(date) Importing docker images from local registry, this might take a while"
-        for image in $(grep image: < /loginvsi/docker-compose.yml | cut -d':' -f2,3| sort | uniq);do
-            docker pull $(echo localhost:55555/$image | xargs) &>> /loginvsi/update.log
-            docker tag $(echo localhost:55555/$image | xargs) $(echo $image | xargs) &>> /loginvsi/update.log
-            docker rmi $(echo localhost:55555/$image | xargs) &>> /loginvsi/update.log
-        done
-        docker pull localhost:55555/portainer &>> /loginvsi/update.log
-        docker tag localhost:55555/portainer portainer &>> /loginvsi/update.log
-        docker rmi localhost:55555/portainer &>> /loginvsi/update.log
-
-        docker rm -f $(docker ps --filter name=update_registry -q) &>> /loginvsi/update.log
-        docker rmi registry:2 &>> /loginvsi/update.log
-        docker rmi $(docker image ls localhost:55555/* --format "{{.Repository}}:{{.Tag}}") &>> /loginvsi/update.log
-        docker rmi $(docker image ls localhost:55555/*/* --format "{{.Repository}}:{{.Tag}}") &>> /loginvsi/update.log
-        rm -rf /tmp/registry_data    
+        # pull images from cdrom instead of online        
+        /loginvsi/bin/update/offlinedockerpull $composefilepath
     fi
 
     docker rm -f portainer &>> /loginvsi/update.log
 
-    netadapters=$(ip -o link show | while read -r num dev fam mtulabel mtusize qlabel queu statelabel state modelabel mode grouplabel group qlenlabel qlen maclabel mac brdlabel brcast; do 
-            if [[ ${mac} != brd && ${mac} != 00:00:00:00:00:00 && ${dev} != br-*  && ${dev} != veth* ]]; then
-                echo ${dev%/*}; 
-            fi
-        done
-        )
-    netadapter=$(echo $netadapters | tail -1 | awk '{split($1,n,":");print n[1]}')
-
-    version=$(grep "Version__Number" < /loginvsi/docker-compose.yml | cut -d':' -f2 | cut -d"'" -f2 | tail -1)
-    applianceversion=$(grep "Appliance_Version" < /loginvsi/docker-compose.yml | cut -d':' -f2 | cut -d"'" -f2 | tail -1)
-    TITLE=$(cat /loginvsi/.title)
-
-    echo "   
-        Welcome to $TITLE - version $version ($applianceversion)
-
-        The Login PI Webinterface is available at: 
-            https://\4{$netadapter}
-            https://\n.\o
-
-        NOTE: Please make sure to update your dns records accordingly
-        "  > /etc/issue    
+    /loginvsi/bin/shared/setwelcomemessage /loginvsi/.env
     # stop identityserver to force new version nr, will get restarted by loginvsid start
     docker service rm VSI_identityserver &>> /loginvsi/update.log
 
