syncing with internal repo

diff --git a/loginvsi/bin/menu/applypfx b/loginvsi/bin/menu/applypfx
--- a/loginvsi/bin/menu/applypfx
+++ b/loginvsi/bin/menu/applypfx
@@ -1,4 +1,5 @@
 #!/bin/bash
+composefilepath=$(grep "COMPOSEFILE=" < /loginvsi/.env | cut -d "=" -f2)
 while :
 do 
     read -erp "Please enter the path to the pfx file: " pfxpath
@@ -13,8 +14,8 @@ if [ -z "$password" ]; then
     exit 1
 fi
 if [ -s "$pfxpath" ]; then
-    openssl pkcs12 -in "$pfxpath" -out /certificates/cert.crt -nokeys -passin pass:$password
-    openssl pkcs12 -in "$pfxpath" -out /certificates/cert.key -nocerts -passin pass:$password -passout pass:$password
+    openssl pkcs12 -in "$pfxpath" -out /certificates/cert.crt -nokeys -passin pass:$password || (echo "Error occured during conversion of pfx to crt, probably incorrect password" && exit 1)
+    openssl pkcs12 -in "$pfxpath" -out /certificates/cert.key -nocerts -passin pass:$password -passout pass:$password || (echo "Error occured during conversion of pfx to crt, probably incorrect password" && exit 1)
 
     # replace the paths in the .env file
     sed -i '/SSL_CERTIFICATE_KEY_PATH=/d' /loginvsi/.env
@@ -32,15 +33,14 @@ if [ -s "$pfxpath" ]; then
     docker secret rm VSI_VSI_SSL_CERTIFICATE &>/dev/null
     docker secret rm VSI_VSI_SSL_CERTIFICATE_KEY &>/dev/null
     echo $password | docker secret create VSI_SSL_CERTIFICATE_KEY_PASSWORD - &>/dev/null
-    #restart portainer and the gateway
-    docker rm -f portainer &>/dev/null
+    
     /usr/bin/loginvsid start
 
-    if [ $(docker service ls -q -f name=VSI_systemconfiguration | wc -l) -gt 0 ]; then
-        docker service update --env-add SystemConfiguration__AllowUntrustedCertificates="false" VSI_systemconfiguration
-        docker service update --env-add SystemConfiguration__AllowUntrustedCertificates="false" VSI_sessionlogonscripts
-        sed -i 's,SystemConfiguration__AllowUntrustedCertificates: "true",SystemConfiguration__AllowUntrustedCertificates: "false",g' /loginvsi/docker-compose.yml
-    fi    
+    for serviceID in $(docker service ls -q);
+    do 
+        docker service update --env-add SystemConfiguration__AllowUntrustedCertificates="false" $serviceID
+    done 
+    sed -i 's,SystemConfiguration__AllowUntrustedCertificates: "true",SystemConfiguration__AllowUntrustedCertificates: "false",g' $composefilepath
 else    
     echo "Could not find valid certificate at $pfxpath"
 fi
